import { Geist, Geist_Mono, Montserrat, Montserrat_Alternates } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar";
import InfiniteMarquee from "../components/marquee";
import Hero from "../components/hero";
import Footer from "../components/footer";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} w-full min-h-screen antialiased overflow-x-hidden`}
        cz-shortcut-listen="true"
      >
        <Navbar />
        <InfiniteMarquee />
        <Hero />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );


}
